# Generated by Django 2.0.2 on 2018-03-25 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('ethinicity', models.CharField(max_length=10, null=True)),
                ('quiteness', models.IntegerField(null=True)),
                ('sanitary', models.IntegerField(null=True)),
                ('timetobed', models.IntegerField(null=True)),
                ('pet', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=10, null=True)),
                ('hobbies', models.CharField(max_length=256, null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('graduationyear', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=256, null=True)),
                ('gid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('floorplan', models.CharField(max_length=5)),
                ('occupied', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('peopleleft', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('admin_uid', models.OneToOneField(db_column='admin_uid', on_delete=django.db.models.deletion.DO_NOTHING, to='app_basic.AdvancedUser')),
                ('aid', models.OneToOneField(db_column='aid', on_delete=django.db.models.deletion.DO_NOTHING, to='app_basic.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_basic.Group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_basic.AdvancedUser')),
            ],
        ),
    ]
