# Generated by Django 2.0.2 on 2018-03-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_basic.User')),
                ('gid', models.IntegerField(default=1)),
                ('gender', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('ehtinicity', models.CharField(max_length=10, null=True)),
                ('quiteness', models.IntegerField(null=True)),
                ('sanitary', models.IntegerField(null=True)),
                ('timetobed', models.IntegerField(null=True)),
                ('pet', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=10, null=True)),
                ('hobbies', models.CharField(max_length=256, null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('graduationyear', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('floorplan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('peopleleft', models.IntegerField()),
                ('aid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app_basic.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_basic.Group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_basic.AdvancedUser')),
            ],
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_basic.Apartment'),
        ),
    ]
