# Generated by Django 2.0.2 on 2018-03-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='potentialmatch',
            unique_together={('uid', 'gid')},
        ),
    ]
