# Generated by Django 2.0.2 on 2018-03-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0002_auto_20180309_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_basic.Apartment'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_basic.User'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='potentialmatch',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_basic.Group'),
        ),
        migrations.AlterField(
            model_name='potentialmatch',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_basic.AdvancedUser'),
        ),
    ]
